# ================= PROMPT LLM =================

def prompt_output(readme, program_output):

    return f"""
You are analyzing the output of a concurrent C program.

Important context:

- The program may be correct.
- In concurrent programs, the order of printed messages may vary.
- Different ordering alone does NOT necessarily indicate an error.

EXERCISE DESCRIPTION:
{readme}

PROGRAM OUTPUT:
{program_output}

Important observations:

- If the program produces NO OUTPUT or the output is empty, this usually indicates a problem in the program (e.g., deadlock, crash, or incorrect logic).
- A correct program for this exercise is expected to produce visible output.
- If the program produces no output at all, you should normally consider the output incorrect.

Task:

Evaluate whether the observed output appears consistent with a correct execution of the program.

Respond ONLY in this format:

OUTPUT_CORRECT: YES or NO
OUTPUT_DIAGNOSIS: <max 3 lines>
"""

def prompt_codice(readme, program_output, code):

    return f"""
You are reviewing C code from a concurrent programming exercise.

Important:

- The program may be correct.
- However, the execution may have failed due to a bug in the code.
- Many concurrency bugs are subtle (race conditions, missing synchronization, incorrect message handling).

EXERCISE DESCRIPTION:
{readme}

PROGRAM OUTPUT:
{program_output}

STUDENT CODE:
{code}

Task:

Evaluate whether the code likely contains a bug.

Focus especially on:

- synchronization errors
- race conditions
- incorrect message queue usage
- incorrect thread logic

If the code clearly appears correct, answer YES.
Otherwise answer NO.

Respond ONLY with:

CODE_CORRECT: YES or NO
CODE_DIAGNOSIS: <max 4 lines>
"""

def prompt_codice_static(readme, code):
    return f"""
You are reviewing the source code of a concurrent C program.

Important guidelines:

- The program may be correct.
- Do NOT assume bugs without clear evidence.
- Some synchronization patterns may appear unusual but still be correct.

EXERCISE DESCRIPTION:
{readme}

STUDENT CODE:
{code}

Analysis process:

1. Look for concrete signs of correctness issues such as:
   - missing synchronization
   - potential race conditions
   - incorrect thread usage
   - unsafe shared resource handling

2. Avoid speculation. Only report issues that are reasonably supported by the code.

3. If the code appears reasonable and no clear problem is visible, assume it is correct.

Respond ONLY with:

CODE_CORRECT: YES or NO
CODE_DIAGNOSIS: <short explanation, max 4 lines>
"""

def prompt_giudice_output(diagnosi, errore_reale):

    return f"""
You are evaluating a diagnosis generated by another LLM.

The program is a concurrent C program.

LLM DIAGNOSIS:
{diagnosi}

REAL ERROR FROM TESTS:
{errore_reale}

Evaluation guidelines:

A diagnosis should be considered CORRECT if:

- it identifies that the output is incorrect
- it proposes a plausible explanation for the failure
- it refers to concurrency or incorrect program behavior

A diagnosis should be considered INCORRECT if:

- it claims the output is correct despite the test failure
- it ignores the failure completely
- it contradicts the observed error

The diagnosis does not need to match the exact wording of the error.

Respond exactly in this format:

DIAGNOSIS_CORRECT: YES or NO
"""

def prompt_giudice_codice(diagnosi, warnings, code_around, solution_code):

    warnings_text = ""
    if warnings:
        warnings_text = "\nSTATIC ANALYSIS WARNINGS:\n" + "\n".join(
            [f"- {w['file']}:{w['line']}: {w['message']}" for w in warnings]
        )

    return f"""
You are evaluating the quality of a diagnosis produced by another LLM.

The task is to determine whether the diagnosis correctly judges if the student's code is correct or incorrect.

LLM DIAGNOSIS:
{diagnosi}

{warnings_text}

STUDENT CODE (relevant excerpt):
{code_around}

REFERENCE SOLUTION (for context):
{solution_code}

Evaluation guidelines:

A diagnosis should be considered CORRECT if:
- it correctly identifies that the code likely contains a problem when warnings indicate issues
- it reasonably explains a concurrency or correctness issue
- it concludes the code is incorrect when clear problems exist

A diagnosis should be considered INCORRECT if:
- it claims the code is correct despite clear warnings or errors
- it describes an unrelated issue
- it misinterprets the code in a major way

The diagnosis does NOT need to mention the exact warning.

Respond exactly in this format:

DIAGNOSIS_CORRECT: YES or NO
"""

def prompt_giudice_codice_static(diagnosi, warnings):
    return f"""
You are evaluating the quality of a diagnosis produced by another LLM.

LLM DIAGNOSIS:
{diagnosi}

STATIC ANALYSIS WARNINGS (ground truth):
{warnings}

Evaluation guidelines:

A diagnosis should be considered CORRECT if:
- it concludes that the code likely contains a problem
- it provides a plausible explanation related to correctness or concurrency

A diagnosis should be considered INCORRECT if:
- it claims the code is correct despite the presence of warnings
- it describes a completely unrelated issue

The diagnosis does NOT need to reference the exact warning.

Respond exactly in this format:

DIAGNOSIS_CORRECT: YES or NO
"""